global using FluentAssertions;
global using Moq;
global using System.Diagnostics.CodeAnalysis;
global using Xunit;
global using YelpAgainstCompanies.Business.Extensions;
global using YelpAgainstCompanies.Business.Services;
global using YelpAgainstCompanies.Domain.Entities;
global using YelpAgainstCompanies.Domain.Exceptions;
global using YelpAgainstCompanies.Domain.Interfaces;
